/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './lib/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    safelist: [
    "bg-[#2563EB]",
    "text-[#2563EB]",
    "dark:bg-[#2563EB]",
    "dark:text-[#2563EB]",
    "hover:bg-[#2563EB]",
    "hover:text-[#2563EB]",
    "bg-[#4B5563]",
    "text-[#4B5563]",
    "dark:bg-[#4B5563]",
    "dark:text-[#4B5563]",
    "hover:bg-[#4B5563]",
    "hover:text-[#4B5563]",
    "bg-[#8B5CF6]",
    "text-[#8B5CF6]",
    "dark:bg-[#8B5CF6]",
    "dark:text-[#8B5CF6]",
    "hover:bg-[#8B5CF6]",
    "hover:text-[#8B5CF6]",
    "bg-[#FFFFFF]",
    "text-[#FFFFFF]",
    "dark:bg-[#FFFFFF]",
    "dark:text-[#FFFFFF]",
    "hover:bg-[#FFFFFF]",
    "hover:text-[#FFFFFF]",
    "bg-[#1F2937]",
    "text-[#1F2937]",
    "dark:bg-[#1F2937]",
    "dark:text-[#1F2937]",
    "hover:bg-[#1F2937]",
    "hover:text-[#1F2937]",
    "bg-[#3B82F6]",
    "text-[#3B82F6]",
    "dark:bg-[#3B82F6]",
    "dark:text-[#3B82F6]",
    "hover:bg-[#3B82F6]",
    "hover:text-[#3B82F6]",
    "bg-[#9CA3AF]",
    "text-[#9CA3AF]",
    "dark:bg-[#9CA3AF]",
    "dark:text-[#9CA3AF]",
    "hover:bg-[#9CA3AF]",
    "hover:text-[#9CA3AF]",
    "bg-[#A78BFA]",
    "text-[#A78BFA]",
    "dark:bg-[#A78BFA]",
    "dark:text-[#A78BFA]",
    "hover:bg-[#A78BFA]",
    "hover:text-[#A78BFA]",
    "bg-[#111827]",
    "text-[#111827]",
    "dark:bg-[#111827]",
    "dark:text-[#111827]",
    "hover:bg-[#111827]",
    "hover:text-[#111827]",
    "bg-[#F3F4F6]",
    "text-[#F3F4F6]",
    "dark:bg-[#F3F4F6]",
    "dark:text-[#F3F4F6]",
    "hover:bg-[#F3F4F6]",
    "hover:text-[#F3F4F6]",
    "bg-[#EED]",
    "text-[#EED]",
    "dark:bg-[#EED]",
    "dark:text-[#EED]",
    "hover:bg-[#EED]",
    "hover:text-[#EED]",
    "bg-[#555]",
    "text-[#555]",
    "dark:bg-[#555]",
    "dark:text-[#555]",
    "hover:bg-[#555]",
    "hover:text-[#555]",
    "bg-[#123]",
    "text-[#123]",
    "dark:bg-[#123]",
    "dark:text-[#123]",
    "hover:bg-[#123]",
    "hover:text-[#123]",
    "bg-[#567]",
    "text-[#567]",
    "dark:bg-[#567]",
    "dark:text-[#567]",
    "hover:bg-[#567]",
    "hover:text-[#567]",
    "bg-[#105]",
    "text-[#105]",
    "dark:bg-[#105]",
    "dark:text-[#105]",
    "hover:bg-[#105]",
    "hover:text-[#105]",
    "bg-[#6E0B8B]",
    "text-[#6E0B8B]",
    "dark:bg-[#6E0B8B]",
    "dark:text-[#6E0B8B]",
    "hover:bg-[#6E0B8B]",
    "hover:text-[#6E0B8B]",
    "bg-[#8E44AD]",
    "text-[#8E44AD]",
    "dark:bg-[#8E44AD]",
    "dark:text-[#8E44AD]",
    "hover:bg-[#8E44AD]",
    "hover:text-[#8E44AD]",
    "bg-[#9B59B6]",
    "text-[#9B59B6]",
    "dark:bg-[#9B59B6]",
    "dark:text-[#9B59B6]",
    "hover:bg-[#9B59B6]",
    "hover:text-[#9B59B6]",
    "bg-[#FFFFFF]",
    "text-[#FFFFFF]",
    "dark:bg-[#FFFFFF]",
    "dark:text-[#FFFFFF]",
    "hover:bg-[#FFFFFF]",
    "hover:text-[#FFFFFF]",
    "bg-[#4A148C]",
    "text-[#4A148C]",
    "dark:bg-[#4A148C]",
    "dark:text-[#4A148C]",
    "hover:bg-[#4A148C]",
    "hover:text-[#4A148C]",
    "bg-[#3600FF]",
    "text-[#3600FF]",
    "dark:bg-[#3600FF]",
    "dark:text-[#3600FF]",
    "hover:bg-[#3600FF]",
    "hover:text-[#3600FF]",
    "bg-[#00FF00]",
    "text-[#00FF00]",
    "dark:bg-[#00FF00]",
    "dark:text-[#00FF00]",
    "hover:bg-[#00FF00]",
    "hover:text-[#00FF00]",
    "bg-[#0000FF]",
    "text-[#0000FF]",
    "dark:bg-[#0000FF]",
    "dark:text-[#0000FF]",
    "hover:bg-[#0000FF]",
    "hover:text-[#0000FF]",
    "bg-[#600]",
    "text-[#600]",
    "dark:bg-[#600]",
    "dark:text-[#600]",
    "hover:bg-[#600]",
    "hover:text-[#600]",
    "bg-[#ACE]",
    "text-[#ACE]",
    "dark:bg-[#ACE]",
    "dark:text-[#ACE]",
    "hover:bg-[#ACE]",
    "hover:text-[#ACE]",
    "bg-[#200]",
    "text-[#200]",
    "dark:bg-[#200]",
    "dark:text-[#200]",
    "hover:bg-[#200]",
    "hover:text-[#200]",
    "bg-[#1A1A1A]",
    "text-[#1A1A1A]",
    "dark:bg-[#1A1A1A]",
    "dark:text-[#1A1A1A]",
    "hover:bg-[#1A1A1A]",
    "hover:text-[#1A1A1A]",
    "bg-[#E5E7EB]",
    "text-[#E5E7EB]",
    "dark:bg-[#E5E7EB]",
    "dark:text-[#E5E7EB]",
    "hover:bg-[#E5E7EB]",
    "hover:text-[#E5E7EB]",
    "bg-[#60A5FA]",
    "text-[#60A5FA]",
    "dark:bg-[#60A5FA]",
    "dark:text-[#60A5FA]",
    "hover:bg-[#60A5FA]",
    "hover:text-[#60A5FA]",
    "bg-[#374151]",
    "text-[#374151]",
    "dark:bg-[#374151]",
    "dark:text-[#374151]",
    "hover:bg-[#374151]",
    "hover:text-[#374151]",
    "bg-[#750]",
    "text-[#750]",
    "dark:bg-[#750]",
    "dark:text-[#750]",
    "hover:bg-[#750]",
    "hover:text-[#750]",
    "bg-[#300]",
    "text-[#300]",
    "dark:bg-[#300]",
    "dark:text-[#300]",
    "hover:bg-[#300]",
    "hover:text-[#300]",
    "bg-[#350]",
    "text-[#350]",
    "dark:bg-[#350]",
    "dark:text-[#350]",
    "hover:bg-[#350]",
    "hover:text-[#350]",
    "bg-[#800]",
    "text-[#800]",
    "dark:bg-[#800]",
    "dark:text-[#800]",
    "hover:bg-[#800]",
    "hover:text-[#800]",
    "bg-[#100]",
    "text-[#100]",
    "dark:bg-[#100]",
    "dark:text-[#100]",
    "hover:bg-[#100]",
    "hover:text-[#100]",
    "bg-[#400]",
    "text-[#400]",
    "dark:bg-[#400]",
    "dark:text-[#400]",
    "hover:bg-[#400]",
    "hover:text-[#400]",
    "bg-[#AFF]",
    "text-[#AFF]",
    "dark:bg-[#AFF]",
    "dark:text-[#AFF]",
    "hover:bg-[#AFF]",
    "hover:text-[#AFF]",
    "bg-[#500]",
    "text-[#500]",
    "dark:bg-[#500]",
    "dark:text-[#500]",
    "hover:bg-[#500]",
    "hover:text-[#500]",
    "bg-[#F40000]",
    "text-[#F40000]",
    "dark:bg-[#F40000]",
    "dark:text-[#F40000]",
    "hover:bg-[#F40000]",
    "hover:text-[#F40000]",
    "bg-[#A20000]",
    "text-[#A20000]",
    "dark:bg-[#A20000]",
    "dark:text-[#A20000]",
    "hover:bg-[#A20000]",
    "hover:text-[#A20000]",
    "bg-[#00FF9D]",
    "text-[#00FF9D]",
    "dark:bg-[#00FF9D]",
    "dark:text-[#00FF9D]",
    "hover:bg-[#00FF9D]",
    "hover:text-[#00FF9D]",
    "bg-[#4F46E5]",
    "text-[#4F46E5]",
    "dark:bg-[#4F46E5]",
    "dark:text-[#4F46E5]",
    "hover:bg-[#4F46E5]",
    "hover:text-[#4F46E5]",
    "bg-[#FF3D6E]",
    "text-[#FF3D6E]",
    "dark:bg-[#FF3D6E]",
    "dark:text-[#FF3D6E]",
    "hover:bg-[#FF3D6E]",
    "hover:text-[#FF3D6E]",
    "bg-[#0A0A0A]",
    "text-[#0A0A0A]",
    "dark:bg-[#0A0A0A]",
    "dark:text-[#0A0A0A]",
    "hover:bg-[#0A0A0A]",
    "hover:text-[#0A0A0A]",
    "bg-[#6366F1]",
    "text-[#6366F1]",
    "dark:bg-[#6366F1]",
    "dark:text-[#6366F1]",
    "hover:bg-[#6366F1]",
    "hover:text-[#6366F1]",
    "bg-[#FF4E7E]",
    "text-[#FF4E7E]",
    "dark:bg-[#FF4E7E]",
    "dark:text-[#FF4E7E]",
    "hover:bg-[#FF4E7E]",
    "hover:text-[#FF4E7E]",
    "bg-[#BEDDED]",
    "text-[#BEDDED]",
    "dark:bg-[#BEDDED]",
    "dark:text-[#BEDDED]",
    "hover:bg-[#BEDDED]",
    "hover:text-[#BEDDED]",
    "bg-[#280]",
    "text-[#280]",
    "dark:bg-[#280]",
    "dark:text-[#280]",
    "hover:bg-[#280]",
    "hover:text-[#280]",
    "bg-[#768]",
    "text-[#768]",
    "dark:bg-[#768]",
    "dark:text-[#768]",
    "hover:bg-[#768]",
    "hover:text-[#768]",
    "bg-[#F5F5F5]",
    "text-[#F5F5F5]",
    "dark:bg-[#F5F5F5]",
    "dark:text-[#F5F5F5]",
    "hover:bg-[#F5F5F5]",
    "hover:text-[#F5F5F5]",
    "bg-[#E6F7FF]",
    "text-[#E6F7FF]",
    "dark:bg-[#E6F7FF]",
    "dark:text-[#E6F7FF]",
    "hover:bg-[#E6F7FF]",
    "hover:text-[#E6F7FF]",
    "bg-[#003A66]",
    "text-[#003A66]",
    "dark:bg-[#003A66]",
    "dark:text-[#003A66]",
    "hover:bg-[#003A66]",
    "hover:text-[#003A66]",
    "bg-[#00FF9D]",
    "text-[#00FF9D]",
    "dark:bg-[#00FF9D]",
    "dark:text-[#00FF9D]",
    "hover:bg-[#00FF9D]",
    "hover:text-[#00FF9D]",
    "bg-[#4F46E5]",
    "text-[#4F46E5]",
    "dark:bg-[#4F46E5]",
    "dark:text-[#4F46E5]",
    "hover:bg-[#4F46E5]",
    "hover:text-[#4F46E5]",
    "bg-[#FF3D6E]",
    "text-[#FF3D6E]",
    "dark:bg-[#FF3D6E]",
    "dark:text-[#FF3D6E]",
    "hover:bg-[#FF3D6E]",
    "hover:text-[#FF3D6E]",
    "bg-[#0A0A0A]",
    "text-[#0A0A0A]",
    "dark:bg-[#0A0A0A]",
    "dark:text-[#0A0A0A]",
    "hover:bg-[#0A0A0A]",
    "hover:text-[#0A0A0A]",
    "bg-[#6366F1]",
    "text-[#6366F1]",
    "dark:bg-[#6366F1]",
    "dark:text-[#6366F1]",
    "hover:bg-[#6366F1]",
    "hover:text-[#6366F1]",
    "bg-[#FF4E7E]",
    "text-[#FF4E7E]",
    "dark:bg-[#FF4E7E]",
    "dark:text-[#FF4E7E]",
    "hover:bg-[#FF4E7E]",
    "hover:text-[#FF4E7E]",
    "bg-[#FFF5E6]",
    "text-[#FFF5E6]",
    "dark:bg-[#FFF5E6]",
    "dark:text-[#FFF5E6]",
    "hover:bg-[#FFF5E6]",
    "hover:text-[#FFF5E6]",
    "bg-[#663C00]",
    "text-[#663C00]",
    "dark:bg-[#663C00]",
    "dark:text-[#663C00]",
    "hover:bg-[#663C00]",
    "hover:text-[#663C00]",
    "bg-[#ECE]",
    "text-[#ECE]",
    "dark:bg-[#ECE]",
    "dark:text-[#ECE]",
    "hover:bg-[#ECE]",
    "hover:text-[#ECE]",
    "bg-[#E0F2FE]",
    "text-[#E0F2FE]",
    "dark:bg-[#E0F2FE]",
    "dark:text-[#E0F2FE]",
    "hover:bg-[#E0F2FE]",
    "hover:text-[#E0F2FE]",
    "bg-[#EAD]",
    "text-[#EAD]",
    "dark:bg-[#EAD]",
    "dark:text-[#EAD]",
    "hover:bg-[#EAD]",
    "hover:text-[#EAD]",
    "bg-[#997]",
    "text-[#997]",
    "dark:bg-[#997]",
    "dark:text-[#997]",
    "hover:bg-[#997]",
    "hover:text-[#997]",
    "bg-[#DED]",
    "text-[#DED]",
    "dark:bg-[#DED]",
    "dark:text-[#DED]",
    "hover:bg-[#DED]",
    "hover:text-[#DED]",
    "bg-[#CED]",
    "text-[#CED]",
    "dark:bg-[#CED]",
    "dark:text-[#CED]",
    "hover:bg-[#CED]",
    "hover:text-[#CED]",
    "bg-[#025]",
    "text-[#025]",
    "dark:bg-[#025]",
    "dark:text-[#025]",
    "hover:bg-[#025]",
    "hover:text-[#025]"
],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: '#2563eb', // Blue 600
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                },
                secondary: {
                    DEFAULT: '#7c3aed', // Violet 600
                    50: '#f5f3ff',
                    100: '#ede9fe',
                    200: '#ddd6fe',
                    300: '#c4b5fd',
                    400: '#a78bfa',
                    500: '#8b5cf6',
                    600: '#7c3aed',
                    700: '#6d28d9',
                    800: '#5b21b6',
                    900: '#4c1d95',
                },
                accent: {
                    DEFAULT: '#db2777', // Pink 600
                    50: '#fdf2f8',
                    100: '#fce7f3',
                    200: '#fbcfe8',
                    300: '#f9a8d4',
                    400: '#f472b6',
                    500: '#ec4899',
                    600: '#db2777',
                    700: '#be185d',
                    800: '#9d174d',
                    900: '#831843',
                },
                background: 'var(--color-background)',
                text: 'var(--color-text)',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic':
                    'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
            },
            typography: theme => ({
                DEFAULT: {
                    css: {
                        color: theme('colors.text'),
                        '--tw-prose-body': theme('colors.text'),
                        '--tw-prose-headings': theme('colors.text'),
                        '--tw-prose-lead': theme('colors.text'),
                        '--tw-prose-links': theme('colors.primary'),
                        '--tw-prose-bold': theme('colors.text'),
                        '--tw-prose-counters': theme('colors.text'),
                        '--tw-prose-bullets': theme('colors.text'),
                        '--tw-prose-hr': theme('colors.text'),
                        '--tw-prose-quotes': theme('colors.text'),
                        '--tw-prose-quote-borders': theme('colors.primary'),
                        '--tw-prose-captions': theme('colors.text'),
                        '--tw-prose-code': theme('colors.text'),
                        '--tw-prose-pre-code': theme('colors.text'),
                        '--tw-prose-pre-bg': theme('colors.background'),
                        '--tw-prose-th-borders': theme('colors.text'),
                        '--tw-prose-td-borders': theme('colors.text'),
                        a: {
                            color: theme('colors.primary'),
                            '&:hover': {
                                color: theme('colors.secondary'),
                            },
                        },
                    },
                },
                dark: {
                    css: {
                        color: theme('colors.text'),
                        a: {
                            color: theme('colors.primary'),
                            '&:hover': {
                                color: theme('colors.secondary'),
                            },
                        },
                        h1: {
                            color: theme('colors.text'),
                        },
                        h2: {
                            color: theme('colors.text'),
                        },
                        h3: {
                            color: theme('colors.text'),
                        },
                        h4: {
                            color: theme('colors.text'),
                        },
                    },
                },
            }),
            keyframes: {
                loading: {
                    '0%, 100%': { height: '10px' },
                    '50%': { height: '40px' },
                },
            },
            animation: {
                loading: 'loading 1s ease-in-out infinite',
            },
            backgroundColor: {
                'section-light': 'var(--section-bg-light)',
                'section-dark': 'var(--section-bg-dark)',
            },
        },
    },
    plugins: [require('@tailwindcss/typography'), require('./lib/theme/tailwind-theme')],
};
