# Reusable style configuration
style_config: &style_config
  label: "Style"
  name: "style"
  widget: "object"
  fields:
    - label: "Background"
      name: "background"
      widget: "select"
      options:
        # Base colors
        - { label: "White", value: "white" }
        - { label: "Light", value: "light" }
        - { label: "Gray", value: "gray" }
        - { label: "Dark", value: "dark" }
        - { label: "Black", value: "black" }
        - { label: "Transparent", value: "transparent" }
        # Brand colors
        - { label: "Primary", value: "primary" }
        - { label: "Secondary", value: "secondary" }
        - { label: "Accent", value: "accent" }
      default: "white"
    - label: "Custom Background Color"
      name: "customBackground"
      widget: "string"
      required: false
      pattern: ['^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', "Must be a valid hex color"]
    - label: "Padding"
      name: "padding"
      widget: "select"
      options:
        - { label: "None", value: "none" }
        - { label: "Small", value: "small" }
        - { label: "Default", value: "default" }
        - { label: "Large", value: "large" }
      default: "default"
    - label: "Width"
      name: "width"
      widget: "select"
      options:
        - { label: "Full Width", value: "full" }
        - { label: "Default", value: "default" }
        - { label: "Narrow", value: "narrow" }
      default: "default"
    - label: "Text Alignment"
      name: "align"
      widget: "select"
      options:
        - { label: "Left", value: "left" }
        - { label: "Center", value: "center" }
        - { label: "Right", value: "right" }
      default: "left"

collections:
  - name: "pages"
    fields:
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Rich Text"
            name: "richText"
            widget: "object"
            summary: '{{fields.content}}'
            fields:
              - {label: "Content", name: "content", widget: "markdown"}
              - *style_config

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Background Image", name: "backgroundImage", widget: "image"}
              - *style_config

          - label: "Features"
            name: "features"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Features"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Icon", name: "icon", widget: "string"}
                  - {label: "URL", name: "url", widget: "string", required: false}
              - *style_config

          - label: "Team"
            name: "team"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Team Members"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Role", name: "role", widget: "string"}
                  - {label: "Bio", name: "bio", widget: "text"}
                  - {label: "Image", name: "image", widget: "image"}
              - *style_config 