# Reusable style configuration
style_config: &style_config
  label: "Style"
  name: "style"
  widget: "object"
  fields:
    - label: "Background"
      name: "background"
      widget: "select"
      options:
        # Base colors
        - { label: "White", value: "white" }
        - { label: "Light", value: "light" }
        - { label: "Gray", value: "gray" }
        - { label: "Dark", value: "dark" }
        - { label: "Black", value: "black" }
        - { label: "Transparent", value: "transparent" }
        # Brand colors
        - { label: "Primary", value: "primary" }
        - { label: "Secondary", value: "secondary" }
        - { label: "Accent", value: "accent" }
      default: "white"
    - label: "Custom Background Color"
      name: "customBackground"
      widget: "string"
      required: false
      pattern: ['^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', "Must be a valid hex color"]
    - label: "Padding"
      name: "padding"
      widget: "select"
      options:
        - { label: "None", value: "none" }
        - { label: "Small", value: "small" }
        - { label: "Default", value: "default" }
        - { label: "Large", value: "large" }
      default: "default"
    - label: "Width"
      name: "width"
      widget: "select"
      options:
        - { label: "Full Width", value: "full" }
        - { label: "Default", value: "default" }
        - { label: "Narrow", value: "narrow" }
      default: "default"
    - label: "Text Alignment"
      name: "align"
      widget: "select"
      options:
        - { label: "Left", value: "left" }
        - { label: "Center", value: "center" }
        - { label: "Right", value: "right" }
      default: "left" 