backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

local_backend: true
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        fields:
          - {label: "Description", name: "description", widget: "text", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: false}
          - {label: "Slug", name: "slug", widget: "string", required: true}
          - label: "Navigation"
            name: "navigation"
            widget: "object"
            fields:
              - {label: "Show in Navigation", name: "show_in_nav", widget: "boolean", default: true}
              - {label: "Show Children", name: "show_children", widget: "boolean", default: false}
              - {label: "Page Weight", name: "page_weight", widget: "number", default: 0}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - {label: "SEO Title", name: "title", widget: "string", required: true}
              - {label: "SEO Description", name: "description", widget: "text", required: true}
              - {label: "Keywords", name: "keywords", widget: "string", required: false}
              - label: "Open Graph"
                name: "og"
                widget: "object"
                fields:
                  - {label: "OG Title", name: "title", widget: "string", required: true}
                  - {label: "OG Description", name: "description", widget: "text", required: true}
                  - {label: "OG Image", name: "image", widget: "image", required: true}
              - label: "Twitter Card"
                name: "twitter"
                widget: "object"
                fields:
                  - {label: "Card Type", name: "card", widget: "select", options: ["summary", "summary_large_image"], default: "summary_large_image"}
                  - {label: "Twitter Title", name: "title", widget: "string", required: true}
                  - {label: "Twitter Description", name: "description", widget: "text", required: true}
                  - {label: "Twitter Image", name: "image", widget: "image", required: true}

      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Background Image", name: "backgroundImage", widget: "image"}

          - label: "Rich Text"
            name: "richText"
            widget: "object"
            fields:
              - {label: "Content", name: "content", widget: "markdown"}
              - {label: "Background Color", name: "backgroundColor", widget: "select", options: ["white", "gray", "primary"], default: "white"}

          - label: "Two Column Text"
            name: "twoColumnText"
            widget: "object"
            fields:
              - {label: "Left Column", name: "leftContent", widget: "markdown"}
              - {label: "Right Column", name: "rightContent", widget: "markdown"}
              - {label: "Column Ratio", name: "ratio", widget: "select", options: ["50/50", "60/40", "40/60"], default: "50/50"}

          - label: "Stats"
            name: "stats"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Stats Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Number", name: "number", widget: "string"}
                  - {label: "Label", name: "label", widget: "string"}

          - label: "Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Testimonials"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Quote", name: "quote", widget: "text"}
                  - {label: "Author", name: "author", widget: "string"}
                  - {label: "Role", name: "role", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", required: false}

          - label: "Timeline"
            name: "timeline"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Events"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Date", name: "date", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}

          - label: "Team"
            name: "team"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Team Members"
                name: "members"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Role", name: "role", widget: "string"}
                  - {label: "Image", name: "image", widget: "image"}

          - label: "Call to Action"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Button Text", name: "buttonText", widget: "string"}
              - {label: "Button Link", name: "buttonLink", widget: "string"}

    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
  - name: "home"
    label: "Homepage"
    files:
      - name: "home"
        label: "Homepage"
        file: "content/home.yml"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - label: "Featured Collections"
            name: "featuredCollections"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Collection"
                name: "collection"
                widget: "string"
                hint: "Enter Shopify collection handle"
          - label: "Content Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "Featured Products"
                name: "featuredProducts"
                widget: object
                fields:
                  - {label: "Section Title", name: "title", widget: "string"}
                  - {label: "Products to Show", name: "count", widget: "number", default: 4}
                  
              - label: "Text Content"
                name: "textContent"
                widget: object
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  
              - label: "Image with Text"
                name: "imageWithText"
                widget: object
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Text", name: "text", widget: "markdown"}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Image Position", name: "imagePosition", widget: "select", options: ["left", "right"]}
    
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "navigation"
        label: "Navigation"
        file: "content/settings/navigation.yml"
        fields:
          - label: "Main Menu"
            name: "mainMenu"
            widget: "list"
            types:
              - label: "Simple Link"
                name: "simpleLink"
                widget: object
                summary: '{{label}}'
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - label: "Link Configuration"
                    name: "link"
                    widget: "list"
                    max: 1
                    min: 1
                    types:
                      - label: "Page Link"
                        name: "pageLink"
                        widget: object
                        summary: 'Page: {{pageLink}}'
                        fields:
                          - label: "Page"
                            name: "pageLink"
                            widget: "relation"
                            collection: "pages"
                            search_fields: ["title"]
                            value_field: "path"
                            display_fields: ["title"]
                      
                      - label: "External Link"
                        name: "externalLink"
                        widget: object
                        summary: 'URL: {{url}}'
                        fields:
                          - label: "URL"
                            name: "url"
                            widget: "string"

              - label: "Nested Pages"
                name: "nestedPages"
                widget: object
                summary: '{{label}} (Auto-nested)'
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - label: "Parent Page"
                    name: "pageLink"
                    widget: "relation"
                    collection: "pages"
                    search_fields: ["title"]
                    value_field: "path"
                    display_fields: ["title"]
                  - label: "Nesting Depth"
                    name: "depth"
                    widget: "number"
                    default: 1
                    min: 1
                    max: 5

              - label: "Manual Children"
                name: "manualChildren"
                widget: object
                summary: '{{label}} (Manual children)'
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - label: "Link Configuration"
                    name: "link"
                    widget: "list"
                    max: 1
                    min: 1
                    types:
                      - label: "Page Link"
                        name: "pageLink"
                        widget: object
                        summary: 'Page: {{pageLink}}'
                        fields:
                          - label: "Page"
                            name: "pageLink"
                            widget: "relation"
                            collection: "pages"
                            search_fields: ["title"]
                            value_field: "path"
                            display_fields: ["title"]
                      
                      - label: "External Link"
                        name: "externalLink"
                        widget: object
                        summary: 'URL: {{url}}'
                        fields:
                          - label: "URL"
                            name: "url"
                            widget: "string"
                  - label: "Children"
                    name: "children"
                    widget: "list"
                    required: false
                    types:
                      - label: "Level 2 Item"
                        name: "level2"
                        widget: object
                        summary: '{{label}}'
                        fields:
                          - {label: "Label", name: "label", widget: "string"}
                          - label: "Link Configuration"
                            name: "link"
                            widget: "list"
                            max: 1
                            min: 1
                            types:
                              - label: "Page Link"
                                name: "pageLink"
                                widget: object
                                summary: 'Page: {{pageLink}}'
                                fields:
                                  - label: "Page"
                                    name: "pageLink"
                                    widget: "relation"
                                    collection: "pages"
                                    search_fields: ["title"]
                                    value_field: "path"
                                    display_fields: ["title"]
                              
                              - label: "External Link"
                                name: "externalLink"
                                widget: object
                                summary: 'URL: {{url}}'
                                fields:
                                  - label: "URL"
                                    name: "url"
                                    widget: "string"
                          - label: "Children"
                            name: "children"
                            widget: "list"
                            required: false
                            types:
                              - label: "Level 3 Item"
                                name: "level3"
                                widget: object
                                summary: '{{label}}'
                                fields:
                                  - {label: "Label", name: "label", widget: "string"}
                                  - label: "Link Configuration"
                                    name: "link"
                                    widget: "list"
                                    max: 1
                                    min: 1
                                    types:
                                      - label: "Page Link"
                                        name: "pageLink"
                                        widget: object
                                        summary: 'Page: {{pageLink}}'
                                        fields:
                                          - label: "Page"
                                            name: "pageLink"
                                            widget: "relation"
                                            collection: "pages"
                                            search_fields: ["title"]
                                            value_field: "path"
                                            display_fields: ["title"]
                                      
                                      - label: "External Link"
                                        name: "externalLink"
                                        widget: object
                                        summary: 'URL: {{url}}'
                                        fields:
                                          - label: "URL"
                                            name: "url"
                                            widget: "string"

      - name: "general"
        label: "General Settings"
        file: "content/settings/general.yml"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Site Logo", name: "siteLogo", widget: "image", required: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
    