backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
local_backend: true
media_folder: public/images
public_folder: /images
collections:
  - name: static
    label: Static
    files:
      - name: site
        label: Site Settings
        file: content/settings/site.json
        fields:
          - name: branding
            label: Branding
            widget: object
            fields:
              - name: name
                label: Site Name
                widget: string
              - name: tagline
                label: Tagline
                widget: string
              - name: description
                label: Description
                widget: text
              - name: logo
                label: Logo Settings
                widget: object
                fields:
                  - name: main
                    label: Main Logo
                    widget: image
                  - name: dark
                    label: Dark Mode Logo
                    widget: image
                  - name: favicon
                    label: Favicon
                    widget: image
                  - name: alt
                    label: Logo Alt Text
                    widget: string
              - name: social
                label: Social Links
                widget: object
                fields:
                  - name: twitter
                    label: Twitter URL
                    widget: string
                    required: false
                  - name: discord
                    label: Discord URL
                    widget: string
                    required: false
                  - name: instagram
                    label: Instagram URL
                    widget: string
                    required: false
                  - name: twitch
                    label: Twitch URL
                    widget: string
                    required: false
          - name: theme
            label: Theme
            widget: object
            fields:
              - name: colors
                label: Light Mode Colors
                widget: object
                fields:
                  - name: primary
                    label: Primary Color
                    widget: color
                  - name: secondary
                    label: Secondary Color
                    widget: color
                  - name: accent
                    label: Accent Color
                    widget: color
                  - name: background
                    label: Background Color
                    widget: color
                  - name: text
                    label: Text Color
                    widget: color
              - name: darkMode
                label: Dark Mode Colors
                widget: object
                fields:
                  - name: primary
                    label: Primary Color
                    widget: color
                  - name: secondary
                    label: Secondary Color
                    widget: color
                  - name: accent
                    label: Accent Color
                    widget: color
                  - name: background
                    label: Background Color
                    widget: color
                  - name: text
                    label: Text Color
                    widget: color
          - name: strings
            label: Site Text
            widget: object
            fields:
              - name: title_template
                label: Title Template
                widget: string
                hint: Use %s for page title
              - name: default_title
                label: Default Title
                widget: string
              - name: default_description
                label: Default Description
                widget: text
              - name: nav
                label: Navigation
                widget: object
                fields:
                  - name: menu_label
                    label: Menu Label
                    widget: string
                  - name: skip_to_content
                    label: Skip to Content Text
                    widget: string
              - name: footer
                label: Footer
                widget: object
                fields:
                  - name: copyright
                    label: Copyright Text
                    widget: string
                    hint: Use {{year}} for current year
              - name: cta
                label: Call to Actions
                widget: object
                fields:
                  - name: default_button
                    label: Default Button Text
                    widget: string
                  - name: contact_button
                    label: Contact Button Text
                    widget: string
                  - name: events_button
                    label: Events Button Text
                    widget: string
              - name: error
                label: Error Messages
                widget: object
                fields:
                  - name: 404_title
                    label: 404 Title
                    widget: string
                  - name: 404_message
                    label: 404 Message
                    widget: text
                  - name: 500_title
                    label: 500 Title
                    widget: string
                  - name: 500_message
                    label: 500 Message
                    widget: text
          - name: seo
            label: SEO Settings
            widget: object
            fields:
              - name: defaultImage
                label: Default OG Image
                widget: image
              - name: twitterHandle
                label: Twitter Handle
                widget: string
              - name: googleAnalyticsId
                label: Google Analytics ID
                widget: string
                required: false
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    preview_path: '{{slug}}'
    preview_template: pages
    preview_component: PagePreview
    nested:
      depth: 100
      summary: '{{title}}'
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Sections
        name: sections
        widget: list
        types:
          - name: richText
            type: richText
            label: Rich Text
            fields:
              - label: Content
                name: content
                widget: markdown
              - label: Style
                name: style
                widget: object
                fields:
                  - label: Layout
                    name: layout
                    widget: object
                    weight: 100
                    fields:
                      - label: Width
                        name: width
                        widget: select
                        options:
                          - label: Full Width
                            value: full
                          - label: Container Width
                            value: container
                          - label: Narrow Width
                            value: narrow
                        default: container
                      - label: Padding
                        name: padding
                        widget: select
                        options:
                          - label: None
                            value: none
                          - label: Small
                            value: small
                          - label: Medium
                            value: medium
                          - label: Large
                            value: large
                        default: medium
                      - label: Vertical Spacing
                        name: verticalSpacing
                        widget: select
                        options:
                          - label: None
                            value: none
                          - label: Small
                            value: small
                          - label: Medium
                            value: medium
                          - label: Large
                            value: large
                        default: medium
                  - label: Appearance
                    name: appearance
                    widget: object
                    weight: 200
                    fields:
                      - label: Background
                        name: background
                        widget: select
                        options:
                          - label: White
                            value: white
                          - label: Light Gray
                            value: lightGray
                          - label: Gray
                            value: gray
                          - label: Dark Gray
                            value: darkGray
                          - label: Black
                            value: black
                          - label: Primary
                            value: primary
                          - label: Secondary
                            value: secondary
                          - label: Accent
                            value: accent
                          - label: Red
                            value: red
                          - label: Orange
                            value: orange
                          - label: Yellow
                            value: yellow
                          - label: Green
                            value: green
                          - label: Blue
                            value: blue
                          - label: Purple
                            value: purple
                          - label: Pink
                            value: pink
                          - label: Custom
                            value: custom
                        default: blue
                      - label: Custom Background Color
                        name: customBackground
                        widget: string
                        required: false
                        pattern:
                          - ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
                          - 'Must be a valid hex color (e.g. #FF0000)'
                        hint: Only used when background is set to "Custom"
                  - label: Typography
                    name: typography
                    widget: object
                    weight: 300
                    fields:
                      - label: Font Size
                        name: fontSize
                        widget: select
                        options:
                          - label: Small
                            value: small
                          - label: Normal
                            value: normal
                          - label: Large
                            value: large
                        default: normal
                      - label: Text Alignment
                        name: alignment
                        widget: select
                        options:
                          - label: Left
                            value: left
                          - label: Center
                            value: center
                          - label: Right
                            value: right
                        default: left
                      - label: Link Style
                        name: linkStyle
                        widget: select
                        options:
                          - label: Underline
                            value: underline
                          - label: No Underline
                            value: no-underline
                          - label: Underline on Hover
                            value: hover-underline
                        default: underline
                      - label: List Style
                        name: listStyle
                        widget: select
                        options:
                          - label: Default
                            value: default
                          - label: No Bullets
                            value: none
                          - label: Custom Bullets
                            value: custom
                        default: default
